version: "3.9"

services:
  selenium:
    image: selenium/standalone-chrome-debug:3.7.1
    ports:
      - 4444:4444
      - 5900:5900
  app:
    image: &app app
    build:
      context: .
    ports:
      - "8000:8000"
    links:
      - selenium
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file: &envfile
      - env.env
    depends_on:
      - db
      - redis
      - broker

  worker:
    build: .
    image: *app
    restart: always
    env_file: *envfile
    command: celery -A app worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - broker

  db:
    image: postgres:10-alpine
    env_file: *envfile
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672



